FROM golang:latest as builder
RUN go get -v github.com/apache/trafficcontrol/traffic_stats
#RUN mkdir -p /go/src/github.com/apache
#WORKDIR src/github.com/apache
#RUN git clone https://github.com/apache/trafficcontrol.git
WORKDIR src/github.com/apache/trafficcontrol
RUN git checkout 3.0.x
RUN mkdir -p /opt/traffic_stats/bin && mkdir -p /opt/traffic_stats/var/run && mkdir -p /opt/traffic_stats/var/log
RUN ls -l .
RUN pwd
RUN ls -l /go/src/github.com/apache
WORKDIR /opt/traffic_stats/bin
RUN go build /go/src/github.com/apache/trafficcontrol/traffic_stats/traffic_stats.go
RUN go build /go/src/github.com/apache/trafficcontrol/traffic_stats/influxdb_tools/create/create_ts_databases.go
RUN go build /go/src/github.com/apache/trafficcontrol/traffic_stats/influxdb_tools/sync/sync_ts_databases.go

FROM centos:7
WORKDIR /opt/traffic_stats

COPY --from=builder /opt/traffic_stats .
COPY --from=builder /go/src/github.com/apache/trafficcontrol/traffic_stats/traffic_stats.cfg /go/src/github.com/apache/trafficcontrol/traffic_stats/traffic_stats_seelog.xml conf/

CMD ["./bin/traffic_stats","-cfg","/opt/traffic_stats/conf/traffic_stats.cfg"]
